version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_server
    ports:
      - "8000:80"
    # volumes:
    #   - ./index.html:/usr/share/nginx/html/index.html:ro
    # depends_on:
    #   - api

  # # Backend FastAPI
  # api:
  #   build: ./api
  #   container_name: backend_api
  #   ports:
  #     - "8000:8000"